Enable API reference docs to show accessor methods (#44)
* Install cupy-core and xarray

The cupy-core package from conda-forge does not bring in CUDA dependencies and thus can be installed on CPU-only CI services. Xref https://github.com/conda-forge/cupy-feedstock/issues/229

* Re-enable building of API page in docs/conf.py

See usage instructions in https://sphinx-autosummary-accessors.readthedocs.io/en/stable/usage.html. Also need to `import cupy_xarray` to fix `exception: no module named xarray.DataArray.cupy` error following https://github.com/xarray-contrib/sphinx-autosummary-accessors/issues/107.

* Undocument Dataset.cupy.get

Fixes `AttributeError: type object 'CupyDatasetAccessor' has no attribute 'get'`

* Pip install cupy_xarray on readthedocs

* Remove numpydoc and use napolean only

* Put editable install in ci/doc.yml so no need to pip install separately

Xref https://docs.readthedocs.io/en/stable/faq.html#i-need-to-install-a-package-in-a-environment-with-pinned-versions

* Add minimal docstrings to accessor methods and attributes

Adding some docstrings to the is_cupy, as_cupy and as_numpy  methods, so that the API docs page looks like center-aligned.

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>